---
title: About this site
published: 2016-05-17
created: 2016-05-17
modified: 2017-09-30
status: ongoing
---

** Purpose

I iterated over a couple of longish drafts for this page. After
reviewing these drafts I realised I could say it better with the
following essential summary:

*This website is my playground and vanity page.*

I anticipate this website will contain both long (gradually expanded and
refined) and short (one-off cruft) content.

Let's see what happens.
** Guidelines
 In the development of this site, there are some general guidelines I have been following:
 - plain and simple[fn::I would love to say minimalist, but it just feels a bit too trendy. Then again... minimalist minimalist minimalist! Errm that word has started to look weird. Definition minimalist: A minimalist is somebody who holds prejudices about minimals. Definition minimals: Animals with a volume typically measured in tens of millilitres. Huh.]
   - in presentation and technology
   - no Javascript
     - I might reluctantly compromise on the no-javascript principle in future, if a particular project or feature depends on it
 - respect visitors[fn::Well, respecting their /privacy/. I don't respect visiting minds in general - refer to the content of this website :)]
   - no services that might implement tracking are included[fn::Unfortunately this might change - Disqus looks pretty attractve on occassion.]
 - openness / freedom (see below)
   - trying to make 'published' the default
   - GPL / CC's licensing

** Technical

This website is generated using [[https://jaspervdj.be/hakyll/][Hakyll]]. Hakyll has provided all I need from a website generation tool - as you can tell by the lack of my tinkering with it. The source of this website is freely available on [[https://github.com/thegaps/bagsend.net][Github]]. If the holes in the networking cheese align, each post will have a working link in the footer to the source document it was produced from[fn::Please take this opportunity to be impressed.].

** Openness
How much of this website and all related material is actually public? The posts are obviously publically available, as is the source code for the site. But there is additional material:
- drafts
- todos and ideas (meta)
- general website organisation notes and scratchpad (meta)
I set out to quantify the amount of material in each category. A naive formualation for the openness of this website can be defined:
#+BEGIN_QUOTE
$$\%openness = \sum lines_{published}/\sum lines_{unpublished}$$
#+END_QUOTE
The intention is that this website will to move towards being 100 % open[fn::I suspect that $lines_{published}$ grows at a faster rate than $lines_{unpublished}$, so this openness metric will probably tend towards 100 % over time anyway, without any special action.].
**** Current status
 | Category  | Num lines |
 |-----------+-----------|
 | Published |      2532 |
 | Draft     |       482 |
 | Meta      |       311 |
 | Total     |      3325 |
 | /% Open/  |   /76.15/ |

** Licence

Unless otherwise noted in the specific resource (webpage, image etc.),
all content of this website is released under the
[[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons
Attribution-ShareAlike 4.0 International License]]. This excludes images and content shared from other sources, which will (hopefully) be noted as appropriate.
# That's right, I can't even give this away!
Code hosted on my [[https://github.com/thegaps][Github]] is under the licence in its repository. 

Finally, while I may strive for accuracy in the minority of posts, I
disclaim that anything I say bears anything more than a passing
resemblance to reality.
